GEMINI_API_KEY = "AIzaSyCOfQTnMDO5AM-17L-3YErL0t3PZP-FaSE"
LANGCHAIN_API_KEY = "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"

[db]
user = "admin"
password = "langchain123"
host = "sample-db.cl0j8hicdoox.us-east-1.rds.amazonaws.com"
name = "classicmodels"
